config/routes.rb
Congresstmi::Application.routes.draw do
 
  devise_for :admins

  resources :users
  root :to => 'users#new'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "is not an email") unless
      value =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  end
end

class User < ActiveRecord::Base
    validates :email, :presence => true, :email => true
    validates_presence_of :name, :address, :zip
    validates_format_of :zip, :with => /^\d{5}(-\d{4})?$/, :message => "should be in the form 12345 or 12345-1234"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :authenticate_admin!, :except => [:new, :create,:show]

  def index
    @users = User.all

    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Submission successfully completed.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stop Cyborg Security Week — a campaign from Fight for the Future</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
</head>
<body>
<div id="wrapper">
  <div id="container">
    <div id="header">
      <ul class="menu">
          <%= render 'devise/menus/registration_items' %>
          <%= render 'devise/menus/login_items' %>
      </ul>
      <div class="wrap">
        <%= link_to(image_tag("header.2.png"), "/")%>
      </div>
    </div>
    <div class="wrap" id="intro">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>
    </div>
  </div>


</div>
</body>
</html>

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

       <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
       </ul>
     </div>
   <% end %>
    <ul>
      <li><%= f.text_field :name, :placeholder=> "Name", :style=> "width:220px" %></li>
      <li><%= f.text_field :email, :placeholder=> "Email", :style=> "width:240px" %></li>
      <li><%= f.text_field :address, :placeholder=> "Address", :style=> "width:280px" %></li>
      <li><%= f.text_field :zip, :placeholder=> "Zip", :style=> "width:80px" %></li>
    </ul>
    <%= f.text_area :text, :value=> "[Insert personal detail here]

    Was that too much information?  Well, with CISPA (the Rogers cybersecurity bill) it seems that Congress will let any company share all my personal data with any government agency, with no limits on how it can be used.  

    Sharing my personal information will do nothing to make the internet more secure.  But if you insist on ending privacy, I figured I would start sharing my personal details with you and your staff, right now.

    Too Much Information?  I agree.", :style=> "width:920px; height: 140px;" %>
    <br style="clear:both">
    <p style="width:920px">Handing government my personal data with no protections does nothing to make the Internet secure. Want to improve cybersecurity? Then why not consult actual security professionals?</p>

    <div class="darker">
      <p> <%= f.check_box :security_professional %> "I'm an Internet security professional, and I'd be happy to explain this. Just write back."</p>
    </div>
    <p class="smaller">Fight For The Future will deliver this email to your Congressperson via their contact form. We will contact you about future campaigns. <a href=" http://fightforthefuture.org/privacy/">Privacy Policy.</a></p>

    <ul style="width:940px;">
      <li><%= f.submit :id=> "gotime", :value=> "Submit", :style=> "float:right" %></li>
    </ul>
  <% end %>

app/views/users/_tweet.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

     <ul>
     <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <h2 style="padding-top: 20px;">Join The Twitter Campaign 
   <%= select_tag "tweet_congress", " ".html_safe %>
   <%image_tag('twitter.png')%></h2><%image_tag('twitter.png', :style=>"float: left; margin-right: 6px;") %>

 <p>#CongressWantsMyData? <input value="I bought icecream for lunch today" name="I bought icecream for lunch today" placeholder="I bought icecream for lunch today" title="I bought icecream for lunch today" required="" id="I bought icecream for lunch today" class="twitter" style="float: none; display: inline; width: 180px;" type="text"> http://is.gd/ablasdfs NO #CISPA<%= f.submit :id=> "gotime", :value=> "Submit", :style=> "float: right;" %></p>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table border="1" style="background-color: #333333; border: 1px solid #555555;">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Zip</th>
    <th>Text</th>
    <th>Security Professional</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.address %></td>
    <td><%= user.zip %></td>
    <td><%= user.text %></td>
    <td><%= user.security_professional %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
   <div id="lead-in">
      <!--          <h1>Congress wants to end our privacy and spy on us with CISPA. Fight back with TMI</h1> -->

      <h2 style="margin-top: 30px;">What is CISPA?</h2>

      <p>A cybersecurity bill that lets any company share your info with anyone. In short, CISPA is the end of meaningful privacy for anyone with personal data on US-based services.</p>

      <h2>What is TMI?</h2>

      <p>They're your inappropriate, awkward, often embarrassing personal details — the kind that the FBI, NSA, CIA, IRS, and local police will soon have access to if CISPA passes.</p>
    </div>

    <div class="wrap" id="twitter">
      <div class="interior">
        <h2 style="padding-top: 20px;">What's the plan?</h2>

        <p>Make Congress embarrassed of their support for CISPA and, well, just embarrassed period.</p>
        <%= render 'tweet' %><br style="clear:both"/>

      </div>
    </div>

    <div class="wrap">
      <div class="buffer">
        <h1>Sound like spying? It is. Write Congress to stop this bill:</h1>
      <%= render 'form' %><br style="clear:both"/>

        <div class="call-to-action">
          <h1>CISPA is the Cybersecurity bill that:</h1>

          <div class="column">
            <h3>Does nothing to secure our infrastructure</h3>

            <p>CISPA contains no provisions to secure the internet, or critical infrastructure <a href="http://www.opencongress.org/bill/112-h3523/news_blogs">read it</a> instead of assuming that data sharing magically solves the problem.</p>
          </div>

          <div class="column">
            <h3>Lets companies share everything with government</h3>

            <p>Its definitions of cybersecurity-related data are so broad that any personal data would qualify. Limits would be easy to defin, but they don’t exist in this bill.</p>
          </div>

          <div class="column">
            <h3>Lets government use data against you, for anything</h3>

            <p>There's not requirement that government use data for cybersecurity. They could use emails to build a criminal case, without a warrant. Any government agancy could get this data: the NSA, FBI, local police — even the IRS!</p>
          </div>

          <div class="column">
            <h3>Overrides all other privacy protections</h3>

            <p>Under CISPA, essential privacy laws governing financial information, medical records, and wiretapping go out the window. Companies’ own privacy promises become moot — CISPA gives them 100% immunity to share.</p>
          </div><%image_tag('shadow.png')%>

          <h1 style="clear: both;"><strong>Want to stop it? Don’t just sign petitions!</strong><br>
          Use this page to write members of Congress directly!</h1>
          <%=image_tag('binoc.badge.png', :style=> "margin-bottom: 30px;")%>
        </div>
      </div>
</div>

app/views/users/show.html.erb
<h2>Thank you for contributing to the discussion.</h2><br/>


<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<p>
  <b>Zip:</b>
  <%= @user.zip %>
</p>